//提示框文字
//编写:wwylele

#include "stdafx.h"
#include "MapDeluxe.h"
#include "MapDeluxeDlg.h"

void CMapDeluxeDlg::InitToolTipText()
{
	m_ToolTip.AddTool(&m_ButtonNew,
		_T("新建一个梦之泉游戏\r\n")
		_T("初次使用本软件请点这里。")
		);
	m_ToolTip.AddTool(&m_ButtonOpen,
		_T("打开一个梦之泉游戏\r\n")
		_T("请不要使用此功能打开非本程序创建的GBA文件！第一次使用本软件请点“新建”。")
		);
	m_ToolTip.AddTool(&m_ButtonSave,
		_T("保存修改\r\n")
		_T("保存后将不能还原，请慎重考虑，如拿不准请备份游戏。")
		);
	m_ToolTip.AddTool(&m_ButtonSaveAs,
		_T("另存为一个新的游戏文件。")
		);
	m_ToolTip.AddTool(&m_ButtonSaveFinal,
		_T("生成一个最终版本的游戏文件。\r\n")
		_T("这个游戏文件将只能进行游戏而不能用本软件进行查看和编辑。\r\n")
		);
	m_ToolTip.AddTool(&m_Tree,
		_T("请在列表中双击一项后在右侧查看和编辑")
		);

	m_ToolTip.AddTool(&m_EditStepNumber,
		_T("【地图在游戏中的位置】\r\n")
		_T("Level和Stage表示什么应该都知道，Step表示此地图在一个关卡中的编号，")
		_T("通常以游戏中顺序排列，但也有例外（比如隐藏房间）。我不让你修改这个是因为修改它会导致")
		_T("游戏ROM遭到严重破坏。")
		);
	m_ToolTip.AddTool(&m_CheckLz77,
		//_T("【地图数据是否被压缩】\r\n")
		_T("这个选项表示了地图数据是否已经被压缩了，它指示游戏应该如何对待地图数据（是解压缩还是直接读取）。")
		_T("\r\n但要注意：这个选项在原始游戏的前8个Level（也就是本程序所能编辑的最大范围）中全部都是选上的，")
		_T("这意味着本程序有理由偷懒而不支持未压缩的数据格式。因此，请保持这个选项的选中\r\n——")
		_T("除非你希望你的游戏变得非常可怕。")
		);
	m_ToolTip.AddTool(&m_ComboBgm,
		_T("这里显示了此地图所用的BGM，可以在下拉框中选择BGM。")
		);
	m_ToolTip.AddTool(&m_ComboSpcMap,
		_T("一般地图只需选择“无”即可。大BOSS关卡需选择“5”。其它值由于只出现于Level9中故此列表不予以列出。")
		_T("\r\n此数值对游戏的影响尚不明确。可能会导致过关事件的变化？")
		);
	TCHAR* str;
	str=_T("【地图剪裁】\r\n")
		_T("地图剪裁会使得地图的边界区域的部分内容将不会再游戏中显示，并对卡比形成一堵“墙”")
		_T("（地图下侧的剪裁则会形成悬崖判定）。左侧和右侧的剪裁宽度是相等的，上侧和下侧同理。")
		_T("\r\n剪裁宽度以像素为单位。");
	m_ToolTip.AddTool(&m_EditClipX,str);
	m_ToolTip.AddTool(&m_EditClipY,str);

	str=_T("【起始坐标】\r\n")
		_T("起始坐标表示了卡比在本地图死亡一次之后将会在哪里出现。")
		_T("如果本地图为本关卡的第一个房间，则起始坐标还代表卡比的初始位置。")
		_T("\r\n坐标以像素为单位。")
		_T("\r\n注：如果坐标位置的判定是墙……你懂的。");
	m_ToolTip.AddTool(&m_EditBeginX,str);
	m_ToolTip.AddTool(&m_EditBeginY,str);

	m_ToolTip.AddTool(&m_EditBckMov,
		_T("这个参数指示了当卡比向前行进时，背景将以多大的速率向前移动。")
		_T("参数的值越大，背景移动越快。\r\n")
		_T("然而，原始游戏中所有地图的这个参数取值只有8和16两种（好像是为了网格对齐？）。")
		_T("当然你也可以填一些其它的值，不过不要太大，否则背景移动过快会导致玩家出现眩晕症状。")
		);
	m_ToolTip.AddTool(&m_EditX36,
		_T("这个参数的作用我尚未查明。")
		_T("原始游戏中所有地图在这个参数上的取值只有0、8、16三种。")
		_T("目前我推测可能和背景移动有关系（可能是垂直移动速率？）。")
		);
	m_ToolTip.AddTool(&m_EditX54,
		_T("这个参数的作用我尚未查明。")
		_T("原始游戏中大部分地图在此处的取值是0，只有少数有其它取值。")
		_T("也许标志了地图某种特殊功能？")
		);
	/*m_ToolTip.AddTool(&m_ComboWind,
		_T("这个参数指示了本地图是否吹有全屏的风以及其风速和风向。")
		_T("如要修改此项，请在下拉列表中选择合适的一项。")
		_T("注意，下拉列表中只显示出原游戏中所出现的各种取值。其它取值有无意义我尚未查明。")
		);*/
	m_ToolTip.AddTool(&m_EditGraAni,
		_T("动态图像库应用于有动态图形（如河流或瀑布等）的地图。")
		_T("\r\n由于此部分的编辑功能尚未完善，目前只提供查看功能。")
		);
	m_ToolTip.AddTool(&m_CheckX3E,
		_T("未知作用的一个选项。")
		_T("不过这个选项在所有的竖版关卡里都选中了。")
		_T("你可以尝试改变一下这个选项帮我研究一下其作用。")
		);
	m_ToolTip.AddTool(&m_CheckX55,
		_T("未知作用的一个选项。")
		_T("不过这个选项在原始游戏的前8个Level（也就是本程序所能编辑的最大范围）中全部都是未选中的。")
		_T("所以如果你不知道它的作用的话，也请保持其未选中状态。")
		);
	m_ToolTip.AddTool(&m_CheckBckRoll,
		_T("这个选项仅在Level4.Stage3（空中飞行艇）中的一些地图上选中了。")
		_T("它的选中标志着，即使卡比处于静止状态，背景也会自动地向前滚动。")
		);
	str=_T("【图形库相关】\r\n")
		_T("这些参数指示了地图所使用的图形库（草地的还是山谷的还是城堡的等等）。")
		_T("\r\n由于此部分的编辑功能尚未完善，目前只提供查看功能。");
	m_ToolTip.AddTool(&m_EditPltFrt,str);
	m_ToolTip.AddTool(&m_EditTillFrt,str);
	m_ToolTip.AddTool(&m_EditGraMapFrt,str);
	m_ToolTip.AddTool(&m_ComboGraFrt,str);
	m_ToolTip.AddTool(&m_EditPltBck,str);
	m_ToolTip.AddTool(&m_EditTillBck,str);
	m_ToolTip.AddTool(&m_EditGraMapBck,str);
	m_ToolTip.AddTool(&m_ComboGraBck,str);

	m_ToolTip.AddTool(&m_CheckNest,
		_T("当这个选项选中的时候，你就进入了“掀开模式”！\r\n")
		_T("在此模式下，你可以编辑星星砖、炸弹砖下面的数据。这些数据很重要")
		_T("，它指示了当砖块被破坏之后此方格的图像和判定将如何变化。")
		_T("有了这个数据后，各种砖块才能显示出其效果。在此模式下没有“掀开数据”的方格将会被涂上阴影。")
		_T("有“掀开数据”的方格将用正常图案显示其图像和判定。在阴影方格上单击左键即可添加掀开数据。")
		_T("在有“掀开数据”的方格上单击右键即可删除“掀开数据”。")
		_T("\n目前已知需要掀开数据的判定有：星星砖、炸弹砖、炸弹连锁砖、连锁炸弹平台、隐藏炸弹砖、钢砖、易碎砖、导火索。")
		);
	m_ToolTip.AddTool(&m_ButtonResize,
		_T("点此可修改地图尺寸\r\n")
		_T("注意：如果修改后的尺寸比原来小，超出尺寸的数据将会被抹杀，不能恢复。")
		);
	m_ToolTip.AddTool(&m_CheckNestAuto,
		_T("自动根据判定填充掀开数据\r\n")
		_T("这个选项是帮助那些死活搞不明白掀开数据时什么的人的，")
		_T("开启这个选项后在正常模式中修改判定数据时，软件将会自动填写相应的掀开数据。\r\n")
		_T("对于所有可击碎砖块而言（星星砖炸弹砖等），掀开数据将会自动填充为空气。")
		_T("对于其他判定，掀开数据将会自动填充为空。")
		);
	m_ToolTip.AddTool(&m_AllowKeyControl,
		_T("如果你希望允许通过键盘控制下方的选择框，请选择这个选项。")
		_T("请用键盘上的WASD键控制。")
		_T("不要忘了把输入法调整到英文状态")
		);
}